POST  https://3001-turquoise-parrot-yhcsmsph.ws-us25.gitpod.io/api/register
content-type: application/json

{
    "username":"zeededero",
    "email": "sampeedadle@gmail.com",
    "password": "1ed2d34"
}


POST  https://3001-turquoise-parrot-yhcsmsph.ws-us25.gitpod.io/api/